platform :ios, '10.0'
use_frameworks!

source 'git@github.com:zhang232425/ZJSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'ZJValidator_Example' do
  
  pod 'ZJValidator', :path => '../'

end
